apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "narthex.fullname" . }}-config
  labels:
    {{- include "narthex.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
