apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "narthex.fullname" . }}-postgres
  labels:
    {{- include "narthex.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "narthex.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "narthex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "narthex.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            {{- toYaml .Values.postgres.command | nindent 12 }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "narthex.fullname" . }}-secrets
                  key: db.user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "narthex.fullname" . }}-secrets
                  key: db.password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "narthex.fullname" . }}-secrets
                  key: db.name
            - name: PGDATA
              value: {{ .Values.postgres.pgData | quote }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      {{- if not .Values.postgres.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
  {{- end }}
